server: 
  port: 9091

spring:
  output:
    ansi:
      enabled: always
  
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver  
    url: jdbc:oracle:thin:@localhost:1521:xe  
    username: tisweekend  
    password: 1234

logging:
  level:
    root: INFO  
    '[com.jjang051.ch04]': DEBUG

mybatis:
  mapper-locations: classpath:mapper/*.xml
