CREATE TABLE BOARD 
(
  NO NUMBER NOT NULL 
, USERNAME VARCHAR2(200) 
, TITLE VARCHAR2(200) 
, CONTENTS VARCHAR2(3000) 
, BOARDGROUP NUMBER 
, BOAARDLEVEL NUMBER 
, BOARDSTEP NUMBER 
, REGDATE DATE 
, HIT NUMBER 
, AVAILABLE NUMBER 
, USERPW VARCHAR2(200) 
, CONSTRAINT BOARD_PK PRIMARY KEY 
  (
    NO 
  )
  ENABLE 
);
