CREATE TABLE MEMBER02 
(
  NO NUMBER NOT NULL 
, USERID VARCHAR2(100 BYTE) NOT NULL 
, USERPW VARCHAR2(100 BYTE) NOT NULL 
, USERNAME VARCHAR2(100 BYTE) NOT NULL 
, USEREMAIL VARCHAR2(100 BYTE) NOT NULL 
, USERADDR VARCHAR2(300 BYTE) 
, REGDATE DATE 
, ZIPCODE NUMBER 
, USERADDRETC VARCHAR2(100 BYTE) 
, CONSTRAINT MEMBER02_PK PRIMARY KEY 
  (
    NO 
  )
  );